mi_app/urls.py
from django.urls import path
from . import views

app_name = "mi_app"
urlpatterns = [
    # ex: /mi_app/
    path('', views.index, name='index'),
    path('<int:depto_id>/', views.detalle_depto, name='detalle_depto'),
    path('<int:depto_id>/detalle_depto/', views.detalle_depto, name='detalle_depto'),
    path('<int:emp_id>/detalle_empleado/', views.detalle_empleado, name='detalle_empleado'),
    path('<int:dept_id>/edita_depto/', views.edita_depto, name='edita_depto'),
    path('<int:dept_id>/set_depto/', views.set_depto, name='set_depto'),
    path('<int:emp_id>/edita_empleado/', views.edita_empleado, name='edita_empleado'),
]

mi_proyecto/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mi_app/', include('mi_app.urls')),
]

mi_app/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    nombre_departamento = models.CharField(max_length=100)
    nombre_gerente = models.CharField(max_length=100)
    creado_depto=models.DateTimeField('Creado Departamento')
    def __str__(self):
        return self.nombre_departamento + \
            " - " + \
            self.nombre_gerente + \
            " - " + \
            str(self.creado_depto)

class Empleado(models.Model):
    departamento=models.ForeignKey(Departamento, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    alias = models.CharField(max_length=50)
    def __str__(self):
        return str(self.departamento) + \
            " - " + \
            self.nombre + \
            " - " + \
            self.alias

mi_app/views.py
import datetime, pytz
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.utils.timezone import utc
from .models import Departamento, Empleado
from django.urls import reverse

# Create your views here.
def index(request):
    todos_departamentos = Departamento.objects.all()
    template = loader.get_template('mi_app/index.html')
    #salida = ', '.join([d.nombre_departamento for d in todos_departamentos])
    #return HttpResponse(salida)
    context = {
        'todos_departamentos': todos_departamentos,
    }
    #return HttpResponse(template.render(context, request))
    return render(request, 'mi_app/index.html', context)

def detalle_depto(request, depto_id):
    #try:
    #    departamento = Departamento.objects.get(pk=depto_id)
    #except Departamento.DoesNotExist:
    #    raise Http404("Lo sentimos, este departamento no existe")
    departamento = get_object_or_404(Departamento, pk=depto_id)

    return render(request, 'mi_app/detalle_depto.html', {'departamento': departamento})

def detalle_empleado(request, emp_id):
    try:
        empleado = Empleado.objects.get(pk=emp_id)
    except Empleado.DoesNotExist:
        raise Http404("Lo sentimos, este empleado no existe")

    return render(request, 'mi_app/detalle_emp.html', {'empleado': empleado})

def edita_depto(request, dept_id):
    departamento = get_object_or_404(Departamento, pk=dept_id)
    return render(request, 'mi_app/edita_depto.html', {'departamento': departamento})

def set_depto(request, dept_id):
    departamento = get_object_or_404(Departamento, pk=dept_id)
    try:
        tz = pytz.timezone('America/Mexico_City')
    except (KeyError, Departamento.DoesNotExist):
        return render(request, 'mi_app:edita_depto', {
            'departamento': departamento,
            'mensaje_error': "No has seleccionado un departamento.",
        })
    else:
        now = datetime.datetime.utcnow().replace(tzinfo=tz)
        departamento.nombre_departamento = request.POST['nombre_departamento']
        departamento.nombre_gerente = request.POST['nombre_gerente']
        departamento.creado_depto = str(now)
        departamento.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('mi_app:edita_depto', args=[departamento.pk]))

def edita_empleado(request, emp_id):
    response = "Estás viendo el listado de los empleados %s."
    return HttpResponse(response % emp_id)

mi_app/templates/mi_app/detalle_depto.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link href="{% static "/css/bootstrap.min.css" %}" rel="stylesheet">
    </head>
    <body>
        <h2>
            Detalles de {{ departamento.nombre_departamento }}
        </h2>
        <hr>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">id </th>
                        <th scope="col">Nombre Departamento</th>
                        <th scope="col">Nombre Gerente</th>
                        <th scope="col">Fecha Creación</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ departamento.id }}</td>
                        <td>{{ departamento.nombre_departamento }}</td>
                        <td>{{ departamento.nombre_gerente }}</td>
                        <td>{{ departamento.creado_depto }}</td>
                    </tr>
                </tbody>
            </table>
            <br>
            <!--
                Django no soporta:
                    - Etiquetas multilínea, por lo tanto, en cada
                      línea se tiene que empezar y terminar el código. 
                    - Terminaciones de instrucción ":" como en python regular
                      para if, for etc. Por lo tanto no se ponen.
                    - Para asignar una variable, se tiene que usar "with" y
                      terminar donde se usa como endwith
            -->
            {% with todos_empleados=departamento.empleado_set.all %}
            {% if todos_empleados %}
                El departamento {{ departamento.nombre_departamento }}, tiene los siguientes empleados:
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">id </th>
                            <th scope="col">Nombre Departamento</th>
                            <th scope="col">Nombre Empleado</th>
                            <th scope="col">Alias</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for empleado in todos_empleados %}
                            <tr>
                                <td>{{ empleado.id }}</td>
                                <th scope="row">{{ empleado.departamento.nombre_departamento }}</th>
                                <td>{{ empleado.nombre }}</td>
                                <td>{{ empleado.alias }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                
            {% endif %}
            {% endwith %}
        <hr>
    </body>
</html>

mi_app/templates/mi_app/detalle_emp.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
            <!-- Required meta tags -->
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

            <!-- Bootstrap CSS -->
            <link href="{% static "/css/bootstrap.min.css" %}" rel="stylesheet">
    </head>
    <body>
        <h2>
            Detalle del empleado {{ empleado.pk }}
        </h2>
		<hr>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">id </th>
                        <th scope="col">nombre departamento</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Alias</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ empleado.id }}</td>
                        <th scope="row">{{ empleado.departamento.nombre_departamento }}</th>
                        <td>{{ empleado.nombre }}</td>
                        <td>{{ empleado.alias }}</td>
                    </tr>
                </tbody>
            </table>
		<hr>
    <body>
</html>

mi_app/templates/mi_app/edita_depto.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
            <!-- Required meta tags -->
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

            <!-- Bootstrap CSS -->
            <link href="{% static "/css/bootstrap.min.css" %}" rel="stylesheet">            
    </head>
    <body>
        <h2>
            Edici&oacute;n de departamento <i>{{ departamento.nombre_departamento }}</i>
        </h2>
        <hr>

        {% if mensaje_error %}
            <p>
                Ocurri&oacute; el siguiente error: <b>{ error_message }</b>
            </p>
        {% endif %}

        <form method="post" action="{% url 'mi_app:set_depto' departamento.id %}">
        
            <!--
                De acuerdo a la documentación, csrf_token sirve para evitar el 
                "cross site forgery" y agregar seguridad a la forma.
            -->
            {% csrf_token %}
            Nombre Departamento:
            <input type="text" name="nombre_departamento" value="{{ departamento.nombre_departamento}}"/>
            <br/>            
            Nombre Gerente:
            <input type="text" name="nombre_gerente" value="{{ departamento.nombre_gerente}}"/>
            <br/>
            <input type="submit" value="Actualizar">
        </form>      
		<hr>
    </body>
</html>

mi_app/templates/mi_app/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
            <!-- Required meta tags -->            
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

            <!-- Bootstrap CSS -->
            <link href="{% static "/css/bootstrap.min.css" %}" rel="stylesheet">            
    </head>
    <body>
        <h2>
            Departamentos disponibles
        </h2>
		<hr>
        {% if todos_departamentos %}
            <ul>
                {% for departamento in todos_departamentos %}
                    <li>
                        <a href="{% url 'mi_app:detalle_depto' departamento.id %}">
                            {{ departamento.nombre_departamento }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No hay departamentos que listar.</p>
        {% endif %}
		<hr>
    <body>
</html>